In [9]:
import sys
import os

# Go up one directory from 'notebooks' to the project root
project_root = os.path.dirname(os.getcwd())

# Add the project root to the list of paths Python searches
if project_root not in sys.path:
    sys.path.append(project_root)

# Now you can import your class
from src.dataset import SQLDataset
import pandas as pd
from transformers import AutoTokenizer
from torch.utils.data import DataLoader

In [10]:
df_val = pd.read_csv('../data/validation.csv')
df_train = pd.read_csv('../data/train.csv')
tokenizer = AutoTokenizer.from_pretrained("t5-small")
max_length=204

In [11]:
train_data = SQLDataset(df_train, tokenizer, max_length)
target_data = SQLDataset(df_val, tokenizer, max_length)


train_dataloader = DataLoader(train_data, batch_size= 16, shuffle = True)
target_dataloader = DataLoader(target_data, batch_size= 16, shuffle = False)

In [14]:
for batch in train_dataloader:
    print("input ids: ")
    print(batch['input_ids'])
    print(batch['input_ids'].shape)
    print("labels: ")
    print( batch['labels'])
    print( batch['labels'].shape)
    print("attention_mask: ")
    print( batch['attention_mask'])
    print( batch['attention_mask'].shape)
    break

input ids: 
tensor([[13959,  1566,    12,  ...,     0,     0,     0],
        [13959,  1566,    12,  ...,     0,     0,     0],
        [13959,  1566,    12,  ...,     0,     0,     0],
        ...,
        [13959,  1566,    12,  ...,     0,     0,     0],
        [13959,  1566,    12,  ...,     0,     0,     0],
        [13959,  1566,    12,  ...,     0,     0,     0]])
torch.Size([16, 204])
labels: 
tensor([[ 3,  2, 31,  ...,  0,  0,  0],
        [ 3,  2, 31,  ...,  0,  0,  0],
        [ 3,  2, 31,  ...,  0,  0,  0],
        ...,
        [ 3,  2, 31,  ...,  0,  0,  0],
        [ 3,  2, 31,  ...,  0,  0,  0],
        [ 3,  2, 31,  ...,  0,  0,  0]])
torch.Size([16, 204])
attention_mask: 
tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]])
torch.Size([16, 204])
